---
- name: Enable community repo for mysql 5.
  set_fact: mysql_enablerepo="mysql56-community"
  when: mysql_version-number == "5"

- name: Enable remi repo for PHP 7.3.
  set_fact: mysql_enablerepo="remi,remi-php73"
  when: mysql_version-number == "3"

