nginx_user: www-data

# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false

nginx_ppa_version: stable
php_install_recommends: false

