---
domain: "test-job"
server_name: "{{ domain }}.lan"

web_root: "/var/www/{{ server_name }}"

phpMyAdmin_src: /usr/share/phpmyadmin
phpMyAdmin_dest: /usr/share/nginx/html

firewall_allowed_tcp_ports:
  - 22
  - 80

nginx_listen_ipv6: true
nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80"
    server_name: "{{ server_name }}"
    root: "{{ web_root }}"
    index: "index.php index.html index.htm"
    state: "present"
    filename: "{{ server_name }}.conf"
    extra_parameters: |
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index app.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            try_files $uri =404;
        }
        location /phpMyAdmin {
            root {{ phpMyAdmin_dest }};
            index index.php index.html index.htm;
            location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }
        }
    

nginx_worker_processes: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"


#mysql

mysql_root_password: "Aiyeejoo4yu6boo1chohj3que9shei_root"
mysql_databases:
  - name: "name_db"
mysql_users:
  - name: "name_user_db"
    password: "Aiyeejoo4yu6boo1chohj3que9shei_user"
    priv: "appDbName.*:ALL"

#replications
mysql_server_id: "1"
mysql_max_binlog_size: "100M"
mysql_binlog_format: "ROW"
mysql_expire_logs_days: "10"
mysql_replication_role: 'master'
# mysql_replication_master: ''
mysql_replication_user: {root}


# php
php_webserver_daemon: "nginx"
php_packages_state: "latest"
php_enable_php_fpm: true
php_packages:
  # - php
  - php-common
  - php-fpm
  - php-opcache
  - php-cli
  - php-mysql
  - php-gd
  - php-mbstring
  - php-mcrypt
  - php-pdo
  - php-pear
  - php-xml
  - php-apcu
  - php-pecl-apcu
  - php-redis