---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - "vars/default.yml"
    - "vars/package_versions.yml"
    - [ "vars/{{ ansible_os_family }}.yml"]

  roles:
  # - install_epel
  # - install_remi
  # - install_nginx
  # - install_php_versions
  # - install_php

  - install_mysql
  # - install_redis
  # - test_task
  # - phpmyadmin
  # - firewall
